language: elixir

sudo: false

elixir:
  - 1.7
  - 1.8

otp_release:
  - 20.3
  - 22.0

script:
  - MIX_ENV=docs mix do deps.get, inch.report
  - MIX_ENV=test mix do deps.get, compile, coveralls.travis

matrix:
  exclude:
  - elixir: 1.7.0
    otp_release: 20.3
