language: elixir

sudo: false

elixir:
  - 1.5
  - 1.6

otp_release:
  - 19.3
  - 20.3

script:
  - MIX_ENV=docs mix do deps.get, inch.report
  - MIX_ENV=test mix do deps.get, compile, coveralls.travis

matrix:
  exclude:
  - elixir: 1.6.0
    otp_release: 18.3
